#!/bin/bash
# ARISG TUNNEL V4 - WEBSOCKET PROXY AUTO INSTALLER
# Ubuntu 22/23/24 - ONE CLICK INSTALL

set -e

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

# Banner
banner() {
    clear
    echo -e "${BLUE}"
    echo "╔══════════════════════════════════════════════════════════════╗"
    echo "║            ARISG TUNNEL V4 - WEBSOCKET PROXY                ║"
    echo "║                    AUTO INSTALLER                           ║"
    echo "╠══════════════════════════════════════════════════════════════╣"
    echo "║  ✅ Python3 WebSocket Proxy Server                          ║"
    echo "║  ✅ Auto Install Dependencies                               ║"
    echo "║  ✅ Systemd Service Auto Start                              ║"
    echo "║  ✅ Firewall Port Auto Open                                 ║"
    echo "║  ✅ Ready for HTTP Custom / OpenVPN WS                      ║"
    echo "╚══════════════════════════════════════════════════════════════╝"
    echo -e "${NC}"
}

info() {
    echo -e "${GREEN}[INFO]${NC} $1"
}

success() {
    echo -e "${GREEN}[SUCCESS]${NC} $1"
}

warning() {
    echo -e "${YELLOW}[WARNING]${NC} $1"
}

error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

# Cek root
if [[ $EUID -ne 0 ]]; then
    error "Jalankan sebagai root (sudo)"
    exit 1
fi

# Konfigurasi Default (bisa diubah)
PROXY_PORT=8080
TARGET_HOST="127.0.0.1"
TARGET_PORT=1194
PASSWORD="arisgtunnel123"
SERVICE_NAME="websocket-proxy"

install_dependencies() {
    info "Menginstall Python3 dan dependencies..."
    apt update
    apt install -y python3 python3-pip python3-venv iptables-persistent curl net-tools
    
    # Buat virtual environment
    python3 -m venv /opt/websocket-proxy
    source /opt/websocket-proxy/bin/activate
    
    success "Dependencies selesai"
}

create_proxy_script() {
    info "Membuat WebSocket Proxy script..."
    
    cat > /opt/websocket-proxy/websocket_proxy.py << 'EOF'
#!/usr/bin/env python3
"""
ARISG TUNNEL V4 - WEBSOCKET PROXY SERVER
Auto-generated by installer
"""

import socket
import threading
import select
import signal
import sys
import time
import os

# Konfigurasi (dari installer)
LISTENING_ADDR = '0.0.0.0'
LISTENING_PORT = int(os.environ.get('PROXY_PORT', '8080'))
TARGET_HOST = os.environ.get('TARGET_HOST', '127.0.0.1')
TARGET_PORT = int(os.environ.get('TARGET_PORT', '1194'))
PASSWORD = os.environ.get('PASSWORD', 'arisgtunnel123')
TIMEOUT = 300
BUFLEN = 65536

WEBSOCKET_RESPONSE = b'HTTP/1.1 101 Switching Protocols\r\nUpgrade: websocket\r\nConnection: Upgrade\r\nSec-WebSocket-Accept: s3pPLMBiTxaQ9kYGzzhZRbK+xOo=\r\n\r\n'
CONNECT_RESPONSE = b'HTTP/1.1 200 Connection established\r\n\r\n'

class ProxyServer:
    def __init__(self):
        self.running = True
        self.clients = []
        self.lock = threading.Lock()
        print("\n🟢 WEBSOCKET PROXY SERVER v4.0 STARTED")
        print(f"📡 Proxy: {LISTENING_ADDR}:{LISTENING_PORT}")
        print(f"🎯 Target: {TARGET_HOST}:{TARGET_PORT}")
        print(f"🔐 Password: {PASSWORD}")
        print("=" * 60)

    def start(self):
        server_socket = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
        server_socket.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
        server_socket.bind((LISTENING_ADDR, LISTENING_PORT))
        server_socket.listen(100)
        
        signal.signal(signal.SIGINT, self.signal_handler)
        signal.signal(signal.SIGTERM, self.signal_handler)
        
        while self.running:
            try:
                client_socket, addr = server_socket.accept()
                handler = ClientHandler(client_socket, addr)
                handler.start()
                with self.lock:
                    self.clients.append(handler)
            except:
                if not self.running:
                    break
        
        server_socket.close()
        self.shutdown()

    def signal_handler(self, signum, frame):
        print("\n🛑 Shutdown signal received...")
        self.running = False

    def shutdown(self):
        print("🔴 Stopping proxy server...")
        with self.lock:
            for client in self.clients[:]:
                client.close()
        print("✅ Proxy server stopped")

class ClientHandler(threading.Thread):
    def __init__(self, client_socket, addr):
        threading.Thread.__init__(self)
        self.client_socket = client_socket
        self.addr = addr
        self.target_socket = None
        self.closed = False

    def log(self, msg):
        print(f"[{time.strftime('%H:%M:%S')}] {self.addr[0]} - {msg}")

    def authenticate(self, data):
        try:
            lines = data.decode('utf-8', errors='ignore').split('\r\n')
            for line in lines:
                if line.startswith('X-Pass:'):
                    passwd = line.split(':', 1)[1].strip()
                    return passwd == PASSWORD
        except:
            pass
        return True

    def handle_handshake(self, data):
        if b'Upgrade: websocket' in data or b'GET / HTTP' in data:
            self.client_socket.send(WEBSOCKET_RESPONSE)
            self.log("✅ WebSocket OK")
            return True
        elif b'CONNECT' in data:
            self.client_socket.send(CONNECT_RESPONSE)
            self.log("✅ CONNECT OK")
            return True
        return False

    def connect_target(self):
        try:
            self.target_socket = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
            self.target_socket.connect((TARGET_HOST, TARGET_PORT))
            self.log(f"🎯 Target connected")
            return True
        except Exception as e:
            self.log(f"❌ Target failed: {e}")
            return False

    def run(self):
        try:
            data = self.client_socket.recv(BUFLEN)
            
            if not self.authenticate(data):
                self.client_socket.send(b'HTTP/1.1 401 Unauthorized\r\n\r\n')
                return

            if not self.handle_handshake(data):
                self.client_socket.send(b'HTTP/1.1 400 Bad Request\r\n\r\n')
                return

            if not self.connect_target():
                return

            sockets = [self.client_socket, self.target_socket]
            while len(sockets) == 2:
                readable, _, _ = select.select(sockets, [], [], 1)
                for sock in readable:
                    try:
                        data = sock.recv(BUFLEN)
                        if not data:
                            sockets.remove(sock)
                            continue
                        if sock == self.client_socket:
                            self.target_socket.sendall(data)
                        else:
                            self.client_socket.sendall(data)
                    except:
                        sockets.remove(sock)
                        break

        except Exception as e:
            self.log(f"❌ Error: {e}")
        finally:
            self.close()

    def close(self):
        try:
            if self.client_socket:
                self.client_socket.close()
        except:
            pass
        try:
            if self.target_socket:
                self.target_socket.close()
        except:
            pass

if __name__ == '__main__':
    proxy = ProxyServer()
    proxy.start()
EOF

    chmod +x /opt/websocket-proxy/websocket_proxy.py
    success "Proxy script dibuat"
}

create_systemd_service() {
    info "Membuat systemd service..."
    
    cat > /etc/systemd/system/$SERVICE_NAME.service << EOF
[Unit]
Description=ARISG Tunnel WebSocket Proxy
After=network.target

[Service]
Type=simple
User=nobody
Group=nogroup
WorkingDirectory=/opt/websocket-proxy
Environment="PROXY_PORT=$PROXY_PORT"
Environment="TARGET_HOST=$TARGET_HOST"
Environment="TARGET_PORT=$TARGET_PORT"
Environment="PASSWORD=$PASSWORD"
ExecStart=/opt/websocket-proxy/bin/python /opt/websocket-proxy/websocket_proxy.py
Restart=always
RestartSec=5

[Install]
WantedBy=multi-user.target
EOF

    systemctl daemon-reload
    systemctl enable $SERVICE_NAME
    success "Systemd service dibuat"
}

setup_firewall() {
    info "Setup firewall iptables..."
    
    apt install -y iptables-persistent
    
    iptables -A INPUT -p tcp --dport $PROXY_PORT -j ACCEPT
    iptables -A INPUT -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT
    iptables -A INPUT -i lo -j ACCEPT
    iptables -P INPUT DROP
    
    netfilter-persistent save
    success "Firewall port $PROXY_PORT dibuka"
}

start_service() {
    info "Start dan test service..."
    systemctl start $SERVICE_NAME
    sleep 3
    
    if systemctl is-active --quiet $SERVICE_NAME; then
        success "Service $SERVICE_NAME ACTIVE"
    else
        error "Service gagal start"
        exit 1
    fi
}

show_config() {
    info "Konfigurasi final:"
    echo "Proxy Port : $PROXY_PORT"
    echo "Target     : $TARGET_HOST:$TARGET_PORT"
    echo "Password   : $PASSWORD"
    echo ""
    echo "Cara koneksi HTTP Custom:"
    echo "SNI         : yourdomain.com"
    echo "Port        : $PROXY_PORT"
    echo "WS Path     : /"
    echo "Header X-Pass: $PASSWORD"
    echo ""
    echo "Service status: systemctl status $SERVICE_NAME"
    echo "Service log  : journalctl -u $SERVICE_NAME -f"
}

main() {
    banner
    
    read -p "Proxy Port (default 8080): " PROXY_PORT_INPUT
    PROXY_PORT=${PROXY_PORT_INPUT:-8080}
    
    read -p "Target Host:Port (default 127.0.0.1:1194): " TARGET_INPUT
    TARGET=${TARGET_INPUT:-127.0.0.1:1194}
    TARGET_HOST=$(echo $TARGET | cut -d: -f1)
    TARGET_PORT=$(echo $TARGET | cut -d: -f2)
    
    read -p "Password (default arisgtunnel123): " PASS_INPUT
    PASSWORD=${PASS_INPUT:-arisgtunnel123}
    
    info "Mulai instalasi dengan konfigurasi:"
    echo "Port  : $PROXY_PORT"
    echo "Target: $TARGET_HOST:$TARGET_PORT"
    echo "Pass  : $PASSWORD"
    echo ""
    read -p "Lanjut? (y/N): " confirm
    [[ $confirm != "y" ]] && exit 0
    
    install_dependencies
    create_proxy_script
    create_systemd_service
    setup_firewall
    start_service
    show_config
    
    success "🎉 INSTALASI SELESAI 100%!"
    success "Service auto start saat boot VPS"
    echo ""
    read -p "Tekan ENTER untuk keluar..."
}

main
